# Generated by Django 5.2.15 on 2026-06-26 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('descripcion', models.CharField(blank=True, max_length=255, verbose_name='Descripción')),
                ('tipo', models.CharField(choices=[('PORCENTAJE', 'Porcentaje (%)'), ('MONTO_FIJO', 'Monto fijo ($)')], default='PORCENTAJE', max_length=15, verbose_name='Tipo')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('monto_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto mínimo')),
                ('max_usos', models.PositiveIntegerField(default=0, help_text='0 = ilimitado', verbose_name='Usos máximos')),
                ('usos_actuales', models.PositiveIntegerField(default=0, verbose_name='Usos actuales')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_expiracion', models.DateTimeField(verbose_name='Fecha de expiración')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
            ],
            options={
                'verbose_name': 'Cupón',
                'verbose_name_plural': 'Cupones',
                'ordering': ['-created_at'],
            },
        ),
    ]
